[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/"
  to = "/pl/"
  status = 302
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/:splat"
  status = 200
  force = true